/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityItem {
  'activityType' : { 'watched' : null } |
    { 'posted' : null },
  'userId' : UserId,
  'timestamp' : bigint,
  'videoId' : string,
}
export interface AdminStats {
  'bannedUsers' : bigint,
  'trendingCount' : bigint,
  'totalWatchEvents' : bigint,
  'totalUsers' : bigint,
}
export type AuthResult = { 'ok' : UserId } |
  { 'err' : string };
export interface CommentView {
  'id' : string,
  'isDeleted' : boolean,
  'parentCommentId' : [] | [string],
  'authorId' : UserId,
  'createdAt' : bigint,
  'text' : string,
  'updatedAt' : bigint,
  'isEdited' : boolean,
  'videoId' : string,
}
export interface ContentStats {
  'totalVideoPosts' : bigint,
  'deletedComments' : bigint,
  'activeVideoPosts' : bigint,
  'totalReactions' : bigint,
  'deletedVideoPosts' : bigint,
  'flaggedVideoPosts' : bigint,
  'totalComments' : bigint,
}
export interface DailyDownloadTotal { 'date' : string, 'count' : bigint }
export interface DownloadAnalytics {
  'byTier' : Array<TierDownloadCount>,
  'dailyTotals' : Array<DailyDownloadTotal>,
  'totalDownloads' : bigint,
  'topUsers' : Array<UserDownloadCount>,
}
export type Language = { 'ar' : null } |
  { 'en' : null };
export type NotificationKind = { 'video_commented' : null } |
  { 'new_video_from_followed' : null } |
  { 'new_follower' : null } |
  { 'video_liked' : null };
export interface NotificationPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'unreadCount' : bigint,
  'items' : Array<NotificationView>,
}
export interface NotificationView {
  'id' : string,
  'userId' : UserId,
  'kind' : NotificationKind,
  'isRead' : boolean,
  'actorId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
  'videoId' : [] | [string],
}
export interface PageResult {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<VideoPostView>,
}
export interface PageResult_1 {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<CommentView>,
}
export type PlanType = { 'annual' : null } |
  { 'monthly' : null };
export type Platform = { 'tiktok' : null } |
  { 'vimeo' : null } |
  { 'kwai' : null } |
  { 'dailymotion' : null } |
  { 'archive' : null } |
  { 'youtube' : null };
export type ReactionKind = { 'like' : null } |
  { 'dislike' : null };
export interface RecommendedVideo {
  'platform' : Platform,
  'score' : number,
  'reason' : string,
  'videoId' : string,
}
export interface RegisterInput {
  'username' : string,
  'displayName' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type SubscriptionStatus = { 'incomplete' : null } |
  { 'active' : null } |
  { 'canceled' : null } |
  { 'pastDue' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null } |
  { 'plus' : null };
export interface SubscriptionView {
  'id' : string,
  'status' : SubscriptionStatus,
  'stripeSubscriptionId' : string,
  'userId' : UserId,
  'tier' : SubscriptionTier,
  'currentPeriodEnd' : Timestamp,
  'stripeCustomerId' : string,
  'planType' : PlanType,
}
export interface TierDownloadCount { 'count' : bigint, 'tier' : string }
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingEntry {
  'video' : VideoMetadata,
  'watchCount' : bigint,
}
export interface UpdateProfileInput {
  'displayName' : string,
  'email' : string,
  'avatarUrl' : string,
  'facebookUrl' : [] | [string],
  'tiktokUrl' : [] | [string],
}
export interface UserDownloadCount { 'userId' : string, 'count' : bigint }
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'username' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'language' : Language,
  'darkMode' : boolean,
  'avatarUrl' : string,
  'isBanned' : boolean,
  'facebookUrl' : [] | [string],
  'tiktokUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings { 'language' : Language, 'darkMode' : boolean }
export type VideoId = string;
export interface VideoMetadata {
  'title' : string,
  'duration' : string,
  'channelTitle' : string,
  'thumbnailUrl' : string,
  'publishedAt' : string,
  'platform' : Platform,
  'viewCount' : string,
  'videoId' : VideoId,
}
export interface VideoPostInput {
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : string,
  'videoUrl' : string,
}
export type VideoPostStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'flagged' : null };
export interface VideoPostView {
  'id' : string,
  'dislikeCount' : bigint,
  'status' : VideoPostStatus,
  'title' : string,
  'likeCount' : bigint,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : bigint,
  'viewCount' : bigint,
  'category' : string,
  'videoUrl' : string,
  'uploaderId' : UserId,
}
export interface VideoStats {
  'dislikeCount' : bigint,
  'likeCount' : bigint,
  'commentCount' : bigint,
}
export interface WatchHistoryEntry {
  'title' : string,
  'thumbnailUrl' : string,
  'watchedAt' : Timestamp,
  'platform' : Platform,
  'videoId' : VideoId,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[string, [] | [string], string], CommentView>,
  'addVideoToPlaylist' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addWatchHistory' : ActorMethod<[WatchHistoryEntry], undefined>,
  'adminDeleteComment' : ActorMethod<[string], boolean>,
  'adminGetContentStats' : ActorMethod<[], ContentStats>,
  'adminListAllComments' : ActorMethod<[bigint, bigint], PageResult_1>,
  'adminListAllVideoPosts' : ActorMethod<[bigint, bigint], PageResult>,
  'adminUpdateVideoPostStatus' : ActorMethod<
    [string, VideoPostStatus],
    [] | [VideoPostView]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'banUser' : ActorMethod<[UserId], undefined>,
  'canUserAccessVideo' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'canUserDownload' : ActorMethod<[string], boolean>,
  'cancelSubscription' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'clearWatchHistory' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [SubscriptionTier, PlanType, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createCustomerPortalSession' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createPlaylist' : ActorMethod<
    [string, string, string, boolean, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createVideoPost' : ActorMethod<[VideoPostInput], VideoPostView>,
  'deleteComment' : ActorMethod<[string], boolean>,
  'deleteCommentByAdmin' : ActorMethod<[string], boolean>,
  /**
   * / Deletes the calling user's account and all associated data. Caller must be authenticated.
   */
  'deleteMyAccount' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'deletePlaylist' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteVideoPost' : ActorMethod<[string], boolean>,
  'deleteVideoPostByAdmin' : ActorMethod<[string], [] | [VideoPostView]>,
  'demoteFromAdmin' : ActorMethod<[UserId], undefined>,
  'editComment' : ActorMethod<[string, string], [] | [CommentView]>,
  'flagVideoPost' : ActorMethod<[string], [] | [VideoPostView]>,
  'followUser' : ActorMethod<[Principal], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getArchiveEnabled' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getContentGatingSettings' : ActorMethod<
    [],
    { 'defaultFreeVideosPerDay' : bigint, 'enabled' : boolean }
  >,
  'getDailyDownloadLimit' : ActorMethod<[], bigint>,
  'getDailymotionApiKey' : ActorMethod<[], string>,
  'getDownloadAnalytics' : ActorMethod<[], DownloadAnalytics>,
  'getDownloadCount' : ActorMethod<[string, string], bigint>,
  'getDownloadLimit' : ActorMethod<[], bigint>,
  'getFlaggedContent' : ActorMethod<[], PageResult>,
  'getFollowActivity' : ActorMethod<[bigint], Array<ActivityItem>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getMyNotifications' : ActorMethod<[bigint, bigint], NotificationPage>,
  'getMySubscription' : ActorMethod<[], [] | [SubscriptionView]>,
  'getPlaylist' : ActorMethod<
    [string],
    {
        'ok' : {
          'id' : string,
          'userId' : string,
          'name' : string,
          'createdAt' : bigint,
          'description' : string,
          'updatedAt' : bigint,
          'isPublic' : boolean,
          'videoIds' : Array<string>,
        }
      } |
      { 'err' : string }
  >,
  'getPremiumVideoIds' : ActorMethod<[], Array<string>>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserPublic]>,
  'getProviderEnabled' : ActorMethod<[string], boolean>,
  'getRecommendations' : ActorMethod<[bigint], Array<RecommendedVideo>>,
  'getSaltForUser' : ActorMethod<[string], [] | [string]>,
  /**
   * / Returns the stored Stripe publishable key (public key, no auth needed).
   */
  'getStripePublishableKey' : ActorMethod<[], string>,
  'getTikTokApiKey' : ActorMethod<[], string>,
  'getTrending' : ActorMethod<[], Array<TrendingEntry>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getUserPlaylists' : ActorMethod<
    [string],
    Array<
      {
        'id' : string,
        'userId' : string,
        'name' : string,
        'createdAt' : bigint,
        'description' : string,
        'updatedAt' : bigint,
        'isPublic' : boolean,
        'videoIds' : Array<string>,
      }
    >
  >,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'getVideoComments' : ActorMethod<[string], Array<CommentView>>,
  'getVideoPost' : ActorMethod<[string], [] | [VideoPostView]>,
  'getVideoReaction' : ActorMethod<[string], [] | [ReactionKind]>,
  'getVideoStats' : ActorMethod<[string], [] | [VideoStats]>,
  'getVimeoApiKey' : ActorMethod<[], string>,
  'getWatchHistory' : ActorMethod<[], Array<WatchHistoryEntry>>,
  'getWebhookEndpointInfo' : ActorMethod<
    [],
    { 'note' : string, 'path' : string }
  >,
  'getYouTubeApiKey' : ActorMethod<[], string>,
  'handleStripeWebhook' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Check if the given username belongs to the admin account.
   * / Used by the frontend to verify admin status without needing II.
   */
  'isAdminUsername' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'linkGoogleAccount' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'listAllUsers' : ActorMethod<[], Array<UserPublic>>,
  'listUserVideoPosts' : ActorMethod<[Principal, bigint, bigint], PageResult>,
  'listVideoPosts' : ActorMethod<[bigint, bigint], PageResult>,
  'loginWithCredentials' : ActorMethod<[string, string], AuthResult>,
  'markAllRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'promoteToAdmin' : ActorMethod<[UserId], undefined>,
  'reactToVideo' : ActorMethod<[string, ReactionKind], boolean>,
  'recordDownload' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<[RegisterInput], UserPublic>,
  'registerWithCredentials' : ActorMethod<
    [string, string, string, string],
    AuthResult
  >,
  'removeVideoFromPlaylist' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Re-seed the admin account. Call this if admin access is lost.
   * / Returns true if seeding succeeded.
   */
  'reseedAdmin' : ActorMethod<[], boolean>,
  'resetDownloadCounts' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[RegisterInput], undefined>,
  'searchYouTube' : ActorMethod<[string, bigint], string>,
  'setArchiveEnabled' : ActorMethod<
    [boolean, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setContentGatingSettings' : ActorMethod<
    [boolean, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDailyDownloadLimitAuth' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDailyDownloadLimitByToken' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDailymotionApiKey' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDailymotionApiKeyByToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDownloadLimit' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setProviderEnabled' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Sets the Stripe publishable key, secret key, and webhook secret.
   * / No caller-based auth since frontend calls are anonymous.
   */
  'setStripeKeys' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Sets Stripe keys after verifying admin credentials.
   * / Accepts the username and client-side password hash (same format as loginWithCredentials).
   */
  'setStripeKeysAuth' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTikTokApiKeyAuth' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTikTokApiKeyWithToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setVideoPremium' : ActorMethod<
    [string, boolean, SubscriptionTier],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setVimeoApiKey' : ActorMethod<[string], undefined>,
  'setVimeoApiKeyAuth' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setVimeoApiKeyByToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setVimeoApiKeyWithToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setYouTubeApiKey' : ActorMethod<[string], undefined>,
  'setYouTubeApiKeyAuth' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setYouTubeApiKeyByToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setYouTubeApiKeyWithToken' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformSubscription' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'unbanUser' : ActorMethod<[UserId], undefined>,
  'unfollowUser' : ActorMethod<[Principal], boolean>,
  'updatePlaylist' : ActorMethod<
    [string, string, string, boolean, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<[UpdateProfileInput], UserPublic>,
  'updateSettings' : ActorMethod<[UserSettings], undefined>,
  'updateVideoPost' : ActorMethod<
    [string, VideoPostInput],
    [] | [VideoPostView]
  >,
  'validateDailymotionApiKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'validateVimeoApiKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'validateYouTubeApiKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyGoogleOAuth' : ActorMethod<[string], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];